"""initial schema portal

Revision ID: 08ae051a99db
Revises: 
Create Date: 2026-04-27 15:18:15.809354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ae051a99db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escolas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=120), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(estado) = 2', name='ck_escola_estado_2chars'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escolas_codigo'), 'escolas', ['codigo'], unique=True)
    op.create_table('coordenadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('primeiro_acesso_token', sa.String(length=64), nullable=True),
    sa.Column('primeiro_acesso_expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordenadores_email'), 'coordenadores', ['email'], unique=True)
    op.create_index(op.f('ix_coordenadores_escola_id'), 'coordenadores', ['escola_id'], unique=False)
    op.create_index(op.f('ix_coordenadores_primeiro_acesso_token'), 'coordenadores', ['primeiro_acesso_token'], unique=False)
    op.create_table('professores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('primeiro_acesso_token', sa.String(length=64), nullable=True),
    sa.Column('primeiro_acesso_expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professores_email'), 'professores', ['email'], unique=True)
    op.create_index(op.f('ix_professores_escola_id'), 'professores', ['escola_id'], unique=False)
    op.create_index(op.f('ix_professores_primeiro_acesso_token'), 'professores', ['primeiro_acesso_token'], unique=False)
    op.create_table('turmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escola_id', sa.UUID(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('serie', sa.String(length=2), nullable=False),
    sa.Column('codigo_join', sa.String(length=64), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("serie IN ('1S', '2S', '3S')", name='ck_turma_serie_em_set'),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turmas_codigo_join'), 'turmas', ['codigo_join'], unique=True)
    op.create_index(op.f('ix_turmas_escola_id'), 'turmas', ['escola_id'], unique=False)
    op.create_index(op.f('ix_turmas_professor_id'), 'turmas', ['professor_id'], unique=False)
    op.create_table('alunos_turma',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('vinculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turma_id', 'telefone', name='uq_aluno_turma_phone')
    )
    op.create_index(op.f('ix_alunos_turma_telefone'), 'alunos_turma', ['telefone'], unique=False)
    op.create_index(op.f('ix_alunos_turma_turma_id'), 'alunos_turma', ['turma_id'], unique=False)
    op.create_table('atividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turma_id', sa.UUID(), nullable=False),
    sa.Column('missao_id', sa.String(length=32), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criada_por_professor_id', sa.UUID(), nullable=False),
    sa.Column('notas_criacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("missao_id IN ('RJ1·OF10·MF', 'RJ1·OF11·MF', 'RJ1·OF12·MF', 'RJ1·OF13·MF', 'RJ1·OF14·MF')", name='ck_atividade_missao_em_whitelist'),
    sa.CheckConstraint('data_fim > data_inicio', name='ck_atividade_intervalo_valido'),
    sa.ForeignKeyConstraint(['criada_por_professor_id'], ['professores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_atividade_turma_missao_inicio', 'atividades', ['turma_id', 'missao_id', 'data_inicio'], unique=False)
    op.create_index(op.f('ix_atividades_data_fim'), 'atividades', ['data_fim'], unique=False)
    op.create_index(op.f('ix_atividades_data_inicio'), 'atividades', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_atividades_turma_id'), 'atividades', ['turma_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_phone', sa.String(length=20), nullable=False),
    sa.Column('aluno_turma_id', sa.UUID(), nullable=True),
    sa.Column('envio_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('turma_id', sa.String(length=255), nullable=True),
    sa.Column('missao_id', sa.String(length=32), nullable=False),
    sa.Column('activity_id', sa.String(length=64), nullable=False),
    sa.Column('foto_path', sa.Text(), nullable=True),
    sa.Column('foto_hash', sa.String(length=64), nullable=True),
    sa.Column('texto_transcrito', sa.Text(), nullable=True),
    sa.Column('ocr_quality_issues', sa.Text(), nullable=True),
    sa.Column('ocr_metrics', sa.Text(), nullable=True),
    sa.Column('redato_output', sa.Text(), nullable=True),
    sa.Column('resposta_aluno', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_turma_id'], ['alunos_turma.id'], ),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], name='fk_interactions_envio', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_aluno_phone'), 'interactions', ['aluno_phone'], unique=False)
    op.create_index(op.f('ix_interactions_aluno_turma_id'), 'interactions', ['aluno_turma_id'], unique=False)
    op.create_index(op.f('ix_interactions_envio_id'), 'interactions', ['envio_id'], unique=False)
    op.create_index('ix_interactions_missao_created', 'interactions', ['missao_id', 'created_at'], unique=False)
    op.create_index('ix_interactions_phone_created', 'interactions', ['aluno_phone', 'created_at'], unique=False)
    op.create_index('ix_interactions_phone_missao_hash', 'interactions', ['aluno_phone', 'missao_id', 'foto_hash'], unique=False)
    op.create_table('envios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atividade_id', sa.UUID(), nullable=False),
    sa.Column('aluno_turma_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_turma_id'], ['alunos_turma.id'], ),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atividade_id', 'aluno_turma_id', name='uq_envio_atividade_aluno')
    )
    op.create_index(op.f('ix_envios_aluno_turma_id'), 'envios', ['aluno_turma_id'], unique=False)
    op.create_index(op.f('ix_envios_atividade_id'), 'envios', ['atividade_id'], unique=False)
    op.create_index(op.f('ix_envios_interaction_id'), 'envios', ['interaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envios_interaction_id'), table_name='envios')
    op.drop_index(op.f('ix_envios_atividade_id'), table_name='envios')
    op.drop_index(op.f('ix_envios_aluno_turma_id'), table_name='envios')
    op.drop_table('envios')
    op.drop_index('ix_interactions_phone_missao_hash', table_name='interactions')
    op.drop_index('ix_interactions_phone_created', table_name='interactions')
    op.drop_index('ix_interactions_missao_created', table_name='interactions')
    op.drop_index(op.f('ix_interactions_envio_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_aluno_turma_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_aluno_phone'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_atividades_turma_id'), table_name='atividades')
    op.drop_index(op.f('ix_atividades_data_inicio'), table_name='atividades')
    op.drop_index(op.f('ix_atividades_data_fim'), table_name='atividades')
    op.drop_index('ix_atividade_turma_missao_inicio', table_name='atividades')
    op.drop_table('atividades')
    op.drop_index(op.f('ix_alunos_turma_turma_id'), table_name='alunos_turma')
    op.drop_index(op.f('ix_alunos_turma_telefone'), table_name='alunos_turma')
    op.drop_table('alunos_turma')
    op.drop_index(op.f('ix_turmas_professor_id'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_escola_id'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_codigo_join'), table_name='turmas')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_professores_primeiro_acesso_token'), table_name='professores')
    op.drop_index(op.f('ix_professores_escola_id'), table_name='professores')
    op.drop_index(op.f('ix_professores_email'), table_name='professores')
    op.drop_table('professores')
    op.drop_index(op.f('ix_coordenadores_primeiro_acesso_token'), table_name='coordenadores')
    op.drop_index(op.f('ix_coordenadores_escola_id'), table_name='coordenadores')
    op.drop_index(op.f('ix_coordenadores_email'), table_name='coordenadores')
    op.drop_table('coordenadores')
    op.drop_index(op.f('ix_escolas_codigo'), table_name='escolas')
    op.drop_table('escolas')
    # ### end Alembic commands ###
