"""m3 auth fields and token blocklist

Revision ID: b8d85498ffd3
Revises: 08ae051a99db
Create Date: 2026-04-27 15:46:39.420891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d85498ffd3'
down_revision: Union[str, Sequence[str], None] = '08ae051a99db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(length=64), nullable=False),
    sa.Column('blocklisted_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exp_original', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blocklist_exp_original'), 'token_blocklist', ['exp_original'], unique=False)
    op.create_index(op.f('ix_token_blocklist_token_jti'), 'token_blocklist', ['token_jti'], unique=True)
    op.add_column('coordenadores', sa.Column('reset_password_token', sa.String(length=64), nullable=True))
    op.add_column('coordenadores', sa.Column('reset_password_expira_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('coordenadores', sa.Column('ultimo_login_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_coordenadores_reset_password_token'), 'coordenadores', ['reset_password_token'], unique=True)
    op.create_foreign_key('fk_interactions_envio', 'interactions', 'envios', ['envio_id'], ['id'], use_alter=True)
    op.add_column('professores', sa.Column('reset_password_token', sa.String(length=64), nullable=True))
    op.add_column('professores', sa.Column('reset_password_expira_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('professores', sa.Column('ultimo_login_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_professores_reset_password_token'), 'professores', ['reset_password_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professores_reset_password_token'), table_name='professores')
    op.drop_column('professores', 'ultimo_login_em')
    op.drop_column('professores', 'reset_password_expira_em')
    op.drop_column('professores', 'reset_password_token')
    op.drop_constraint('fk_interactions_envio', 'interactions', type_='foreignkey')
    op.drop_index(op.f('ix_coordenadores_reset_password_token'), table_name='coordenadores')
    op.drop_column('coordenadores', 'ultimo_login_em')
    op.drop_column('coordenadores', 'reset_password_expira_em')
    op.drop_column('coordenadores', 'reset_password_token')
    op.drop_index(op.f('ix_token_blocklist_token_jti'), table_name='token_blocklist')
    op.drop_index(op.f('ix_token_blocklist_exp_original'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
